/** Site-wide SEO + NAP constants for Siddhivinayak Overseas (Surat). */

export const SITE_URL = 'https://siddhivinayakoverseas.com'
export const SITE_NAME = 'Siddhivinayak Overseas'
export const SITE_TAGLINE = 'Visa & Overseas Education Consultants in Surat'

export const NAP = {
  legalName: 'Siddhivinayak Overseas',
  streetAddress: '620, 6th Floor, Pragti IT Park, Kiran Chowk to Yogi Chowk Road',
  addressLocality: 'Surat',
  addressRegion: 'Gujarat',
  postalCode: '395006',
  addressCountry: 'IN',
  fullAddress:
    '620, 6th Floor, Pragti IT Park, Kiran Chowk to Yogi Chowk Road, Surat, Gujarat, India',
  phoneIN: '+919512000632',
  phoneINDisplay: '+91 95120 00632',
  phone2IN: '+919512000632',
  phone2INDisplay: '+91 95120 00632',
  email: 'info@siddhivinayakoverseas.com',
  whatsappUrl: 'https://wa.me/919512000632',
  /** Office WhatsApp that answers the applicant dashboard's Officer Chat. */
  officeChatWhatsApp: '919512000632',
  officeChatWhatsAppDisplay: '+91 95120 00632',
  geo: {
    latitude: 21.1702,
    longitude: 72.8311,
  },
} as const

/**
 * The shared-link preview image. 1200x630 because every consumer of og:image —
 * Facebook, WhatsApp, LinkedIn, X's `summary_large_image` — lays a link card out
 * at 1.91:1, and it is also wide enough for Google's structured-data image
 * guidance. Generated by `npm run images`; see the SOCIAL block in
 * scripts/optimize-images.mjs for how and from what.
 */
export const DEFAULT_OG_IMAGE = `${SITE_URL}/og-default.jpg`
export const DEFAULT_OG_IMAGE_WIDTH = 1200
export const DEFAULT_OG_IMAGE_HEIGHT = 630

/** Official social profiles. Used for footer/contact links and schema.org `sameAs`. */
export const SOCIAL_LINKS = {
  instagram: {
    label: 'Instagram',
    handle: '@siddhivinyakoverseas',
    url: 'https://www.instagram.com/siddhivinyakoverseas/',
  },
  facebook: {
    label: 'Facebook',
    handle: 'Siddhivinayak Overseas',
    url: 'https://www.facebook.com/share/1EMjNkoty3/',
  },
} as const

export const SOCIAL_SAME_AS: string[] = Object.values(SOCIAL_LINKS).map((profile) => profile.url)

/** WhatsApp chat link to the Officer Chat number with the message pre-filled. */
export function officeChatWhatsAppUrl(text: string): string {
  return `https://wa.me/${NAP.officeChatWhatsApp}?text=${encodeURIComponent(text)}`
}

/**
 * Builds the canonical absolute URL for a route.
 *
 * Normalisation matters here because the value is emitted as the canonical and
 * og:url, and must match the sitemap exactly — Google treats
 * `…/study-visa` and `…/study-visa/` as different URLs. The rules mirror
 * public/.htaccess: no trailing slash except on the root, and no query string or
 * fragment (neither ever identifies a distinct canonical page on this site).
 */
export function absoluteUrl(path: string): string {
  if (!path || path === '/') return `${SITE_URL}/`

  let normalized = path.startsWith('/') ? path : `/${path}`
  normalized = normalized.split('#')[0].split('?')[0]
  if (normalized.length > 1 && normalized.endsWith('/')) normalized = normalized.slice(0, -1)

  return normalized === '/' ? `${SITE_URL}/` : `${SITE_URL}${normalized}`
}
